-- =============================================================================
-- Yoga Curriculum App — Seed Data (DML)
-- =============================================================================
-- AUTO-GENERATED by scripts/generate-seed.ts
-- DO NOT EDIT THIS FILE MANUALLY — edit the CSV files in src/data/ instead.
-- Generated at: 2026-08-06T08:02:46.232Z
-- =============================================================================

-- asanams
-- Generated from asanams.csv
-- ---------------------------------------------------------------
INSERT OR IGNORE INTO asanams (
    asanam_id, asanam_sequence_id, no_of_cycles, guided_instructions_audio_url, asanam_video_url, asanam_audio_change_step_timestamps
) VALUES
(1, 1, 12, 'assets/asanams/surya_namaskar/audio/guide.mp3', 'assets/asanams/surya_namaskar/video/demo.mp4', '[[0.0, 4.5], [4.5, 9.0], [9.0, 14.2], [14.2, 19.8], [19.8, 25.0]]'),
(2, 2, 1, 'assets/asanams/padmasana/audio/guide.mp3', 'assets/asanams/padmasana/video/demo.mp4', '[[0.0, 6.0], [6.0, 12.5], [12.5, 20.0]]'),
(3, 3, 3, 'assets/asanams/trikonasana/audio/guide.mp3', 'assets/asanams/trikonasana/video/demo.mp4', '[[0.0, 5.0], [5.0, 10.5], [10.5, 16.0], [16.0, 22.0]]')
;

-- asanam_steps
-- Generated from asanam_steps.csv
-- ---------------------------------------------------------------
INSERT OR IGNORE INTO asanam_steps (
    asanam_step_id, asanam_id, step_sequence_id, step_name, step_description, step_image_url
) VALUES
(1, 1, 1, 'Pranamasana (Prayer Pose)', 'Stand at the edge of your mat, keep your feet together and balance your weight equally on both feet. Expand your chest and relax your shoulders.', 'assets/asanams/surya_namaskar/steps/01_pranamasana.png'),
(2, 1, 2, 'Hastauttanasana (Raised Arms Pose)', 'Breathe in and lift the arms up and back, keeping the biceps close to the ears. Stretch the whole body up from the heels to the tips of the fingers.', 'assets/asanams/surya_namaskar/steps/02_hastauttanasana.png'),
(3, 1, 3, 'Hastapadasana (Standing Forward Bend)', 'Breathe out and bend forward from the waist keeping the spine erect. Bring the hands down to the floor beside the feet.', 'assets/asanams/surya_namaskar/steps/03_hastapadasana.png'),
(4, 1, 4, 'Ashwa Sanchalanasana (Equestrian Pose)', 'Breathe in and push your right leg back as far as possible. Bring the right knee to the floor and look up.', 'assets/asanams/surya_namaskar/steps/04_ashwa_sanchalanasana.png'),
(5, 1, 5, 'Dandasana (Stick Pose)', 'Breathe in and take the left leg back, bringing the whole body in a straight line.', 'assets/asanams/surya_namaskar/steps/05_dandasana.png'),
(6, 2, 1, 'Seated Position', 'Sit on the floor with legs stretched out in front of you, spine erect.', 'assets/asanams/padmasana/steps/01_seated.png'),
(7, 2, 2, 'Half Lotus', 'Bend the right knee and place the right foot on the left thigh. The sole should face upward and the heel close to the abdomen.', 'assets/asanams/padmasana/steps/02_half_lotus.png'),
(8, 2, 3, 'Full Lotus', 'Repeat with the left leg, placing the left foot on the right thigh. Place the hands on the knees in mudra position.', 'assets/asanams/padmasana/steps/03_full_lotus.png'),
(9, 3, 1, 'Standing Wide-Legged', 'Stand straight with your feet wide apart. Turn your right foot out 90 degrees and left foot in by about 15 degrees.', 'assets/asanams/trikonasana/steps/01_standing.png'),
(10, 3, 2, 'Arms Extended', 'Raise both arms to shoulder height, parallel to the floor, palms facing downward.', 'assets/asanams/trikonasana/steps/02_arms_extended.png'),
(11, 3, 3, 'Lateral Bend', 'Exhale and bend your body to the right from the hips. Let the right hand touch the right ankle while extending the left arm straight up.', 'assets/asanams/trikonasana/steps/03_lateral_bend.png'),
(12, 3, 4, 'Hold and Return', 'Hold the pose while stretching. Look up at the left palm. Inhale and come up slowly. Repeat on the other side.', 'assets/asanams/trikonasana/steps/04_hold_return.png')
;
